### ISSUE TITLE
Doesn't seem to properly work.

### ISSUE THREAD

**Issue by Mephistowastaken** [thatguystone/lintartarus#1]
I have to issues, I still have no idea what make does and the "sudo ./lintartarus --authorize" doesn't do a thing.

**Comment by thatguystone** [comment]
1. Make generates the `lintartarus` binary.
2. `sudo ...` places a file at `/etc/udev/rules.d/99-lintartarus.rules` that contains udev rules so that users of group plugdev can mess with the device.
